Im folgenden Kapitel wird zunächst eine Zusammenfassung dieser Arbeit formuliert. Anschließend wird ein Ausblick auf mögliche zukünftige Entwicklungen gegeben.

== Zusammenfassung
Das Ziel dieser Arbeit lag in der Konzeption und Implementierung einer Augmented-Reality-Konstruktionsumgebung für Möbelsysteme auf Basis von WebXR. Auf Grundlage einer Analyse des Standes der Technik sowie der theoretischen Grundlagen wurde ein Konzept für die Anwendung entwickelt und anschließend implementiert. Darüber hinaus wurde die Anwendung im Rahmen der Arbeit von Maximilian Patzke in ein bestehendes System integriert.

Hierbei konnte das Konzept in Bezug auf die technische Umsetzung erfolgreich umgesetzt werden und durch die Integration in das Shop-System von Maximilian Patzke konnte die Anwendung in einem breiteren Kontext getestet werden. Um die Usability und User Experience der Anwendung zu evaluieren, wurde eine Studie entwickelt und durchgeführt. Die Studie lässt die Schlussfolgerung zu, dass die Anwendung eine positive Usability sowie User Experience bietet. Darüber hinaus konnte durch die Einbindung der Evaluation von Maximilian Patzke hervorgehoben werden, dass die Anwendung auch in ein externes System integriert werden kann und hierbei beim Entscheidungsprozess unterstützt.

Es lässt sich somit feststellen, dass sich mithilfe von WebXR eine komplexe AR-Anwendung entwickeln lässt, die sowohl auf technischer als auch in der Usability und User Experience funktional und positiv bewertet wird. WebXR erweist sich daher als eine valide Alternative im Bereich der Augmented-Reality-Technologien.

== Ausblick
Augmented Reality hat sich in den letzten Jahren zu einer bedeutenden Technologie entwickelt. Im Rahmen dieser Arbeit wurde der aktuelle Stand der Technik analysiert und verschiedene Beispielanwendungen vorgestellt, die Augmented Reality bereits in der Möbelbranche einsetzen.

Diese Untersuchung zeigt, dass Augmented Reality in einer Vielzahl von Anwendungen im Bereich der Möbelbranche verwendet wird. Die meisten dieser Anwendungen werden als native Anwendungen entwickelt und beschränken sich hauptsächlich auf die Visualisierung von Möbelstücken. Diese Arbeit demonstriert, dass WebXR eine valide Alternative für die Entwicklung von Augmented Reality Anwendungen in der Möbelbranche darstellt. Die Ergebnisse der durchgeführten Studie stimmen mit weiteren Forschungen in diesem Bereich überein und zeigen, dass die Usability und User Experience der Anwendung positiv bewertet wird.

Allerdings müssen die Ergebnisse der Studie aufgrund der hohen Streuung kritisch betrachtet werden. Daher sollte diese Arbeit als Grundlage für weiterführende Forschungen und Entwicklungen dienen. Die Interaktion der Anwendung stellt ihr Alleinstellungsmerkmal im Vergleich mit anderen Anwendungen dar. Gerade diese Interaktion erfordert weitere Untersuchungen. Im Rahmen dieser Arbeit wurde nur eine einzige Form der Interaktion implementiert. Es ist jedoch denkbar, dass zusätzliche Interaktionsformen die Usability und User Experience der Anwendung weiter verbessern könnten. Zukünftige Forschungen könnten verschiedene Interaktionsmethoden miteinander vergleichen, um die optimale Lösung zu identifizieren.

Darüber hinaus kann die Funktionalität der Anwendung auf weitere Möbelsysteme erweitert werden. Dies könnte die Anwendbarkeit und den Nutzen der Anwendung erheblich steigern. Außerdem besteht die Möglichkeit, die entwickelte Anwendung als Grundlage für neue, innovative Anwendungen zu nutzen, die über die ursprünglichen Anwendungsfälle hinausgehen. Die Integration der Anwendung in andere Systeme ist ebenfalls ein vielversprechender Forschungsansatz. Durch die Einbindung in bestehende Systeme könnte die Anwendung nahtlos in verschiedene Arbeitsabläufe integriert werden, was die Effizienz und Benutzerfreundlichkeit weiter erhöhen würde. Zukünftige Arbeiten sollten diese Integrationsmöglichkeiten genauer untersuchen und mögliche Synergien mit anderen Technologien und Systemen evaluieren.

Zusammenfassend lässt sich sagen, dass Augmented Reality in der Möbelbranche ein enormes Potenzial hat. Diese Arbeit liefert eine Grundlage für weitere Forschungen und Entwicklungen in diesem Bereich, mit dem Ziel, die Interaktion, Usability und Funktionalität von Augmented Reality Anwendungen kontinuierlich zu verbessern und zu erweitern.