In diesem Kapitel werden verschiedene AR-Plattformen anhand spezifischer Kriterien untersucht. Die Kriterien umfassen Kompatibilität, Leistungsfähigkeit, Benutzerfreundlichkeit, Zukunftssicherheit und Kosten. Nach einer Beschreibung dieser Kriterien erfolgt eine Vorstellung und ein Vergleich der Plattformen WebXR, ARKit, ARCore und Vuforia. Obwohl der Fokus dieser Arbeit auf der Entwicklung einer Augmented Reality Anwendung mit WebXR liegt, werden auch native AR-Plattformen betrachtet, um ein umfassendes Verständnis der verfügbaren Technologien zu gewährleisten. Es handelt sich hierbei um eine gezielte Auswahl relevanter AR-Plattformen und nicht um eine vollständige Marktanalyse.

=== Kriterien
Kompatibilität bezieht sich darauf, welche Geräte und Betriebssysteme von der jeweiligen Plattform unterstützt werden. Eine breite Kompatibilität ermöglicht eine größere Reichweite und Flexibilität bei der Anwendungserstellung. Leistungsfähigkeit umfasst die Render-Qualität und die Latenzzeiten, die maßgeblich die Nutzererfahrung beeinflussen. Plattformen, die hohe Leistungsstandards erfüllen, können realistischere und flüssigere AR-Erlebnisse bieten. Benutzerfreundlichkeit betrachtet die Entwicklungsumgebung und die verfügbaren Tools. Eine benutzerfreundliche Plattform bietet eine intuitive Entwicklungsumgebung, umfangreiche Dokumentation und aktiven Community-Support, was den Entwicklungsprozess erleichtert und beschleunigt. Zukunftssicherheit beschäftigt sich mit der langfristigen Unterstützung und Weiterentwicklung der Plattform. Plattformen, die regelmäßig aktualisiert werden und von großen Unternehmen oder Gemeinschaften unterstützt werden, bieten eine höhere Investitionssicherheit. Kosten umfassen sowohl Lizenzkosten als auch Entwicklungs- und Wartungskosten. Kosteneffiziente Plattformen ermöglichen es Entwicklern, hochwertige Anwendungen zu geringeren Kosten zu erstellen und zu betreiben.

=== WebXR
WebXR beschreibt eine API, welche es ermöglicht, plattformübergreifend Augmented Reality Anwendungen zu entwickeln und bereitzustellen. Die API unterstützt eine Vielzahl von Geräten, einschließlich Smartphones, Tablets und Headsets, unabhängig vom Betriebssystem @webxr-spec.

In Bezug auf die Leistungsfähigkeit bietet WebXR eine angemessene Render-Qualität und akzeptable Latenzzeiten für webbasierte Anwendungen. WebXR verwendet native Plattformen wie ARCore auf Android-Geräten, um eine angemessene Leistung zu gewährleisten. Allerdings kann dadurch nicht die gleiche Leistungsfähigkeit erreicht werden wie bei der direkten Nutzung von beispielsweise ARCore. Bei WebXR handelt es sich um einen W3C-Standard, der von der Immersive Web Working Group entwickelt wird. Es wird eine offizielle Dokumentation bereitgestellt sowie eine Auswahl an offiziellen Beispielen. Die Integration in bestehende Web-Technologien ist möglich, wodurch auf bekannte Web-Entwicklungstools und -Frameworks zurückgegriffen werden kann. Dadurch, dass es sich bei der WebXR Device API um einen offenen W3C-Standard handelt, ist die Zukunftssicherheit gewährleistet. Die API wird von großen Technologieunternehmen wie Google und Mozilla unterstützt und kontinuierlich weiterentwickelt. Die breite Unterstützung trägt zur Stabilität und Weiterentwicklung der Plattform bei. Was die Kosten betrifft, so entstehen für WebXR keine Lizenzkosten, was es zu einer kosteneffizienten Wahl für Entwickler macht. Die Entwicklungs- und Wartungskosten sind geringer, da keine speziellen Entwicklungsumgebungen oder -tools benötigt werden.

=== ARKit
ARKit ist eine von Apple entwickelte Plattform für Augmented Reality-Anwendungen, die exklusiv auf kompatiblen iOS-Geräten genutzt werden kann @apple-developer-ar.

In Bezug auf die Leistungsfähigkeit bietet ARKit eine gute Render-Qualität und niedrige Latenzzeiten, da es speziell für die Prozessoren und Grafikchips von Apple-Geräten entwickelt wurde. Diese Plattform nutzt die integrierten Sensoren und Kameras der Geräte, um präzise AR-Erlebnisse zu ermöglichen. Dazu gehören unter anderem Bewegungsverfolgung, Gesichts- und Objekterkennung sowie Umgebungswahrnehmung. Apple stellt umfangreiche Dokumentationen, Tutorials und Beispielprojekte zur Verfügung, die den Einstieg in die ARKit-Entwicklung erleichtern. Außerdem ist ARKit nahtlos in die Xcode-Entwicklungsumgebung integriert, was eine effiziente Entwicklung und Optimierung von AR-Anwendungen ermöglicht. Apple veröffentlicht regelmäßig Updates und neue Versionen von ARKit, die zusätzliche Funktionen und verbesserte Leistungsfähigkeit bieten. Zudem zeigt Apple beispielsweise durch die Veröffentlichung der Apple Vision Pro ein hohes Interesse am Bereich der Augmented Reality. Für die Nutzung von ARKit selbst enstehen keine zusätzlichen Lizenzkosten, da es in das iOS-Entwicklerprogramm integriert ist. Allerdings sind Apple-Geräte erforderlich, was höhere Hardware- und Softwarekosten im Vergleich zu plattformübergreifenden Lösungen wie WebXR bedeuten kann.

=== ARCore
ARCore ist eine von Google entwickelte Plattform für Augmented Reality-Anwendungen, die auf einer Vielzahl von Android-Geräten genutzt werden kann. Einige bereitgstellte APIs sind auch Platformübergreifend für iOS verfügbar. Demenstprechend können ARCore Anwendungen als plattformübergreifende Lösung entwickelt werden @arcore-documentation.

In Bezug auf die Leistungsfähigkeit bietet ARCore eine gute Render-Qualität und niedrige Latenzzeiten, da es speziell für die Prozessoren und Grafikchips von Android-Geräten entwickelt wurde. ARCore nutzt die integrierten Sensoren und Kameras der Geräte, um präzise AR-Erlebnisse zu ermöglichen. Zu den Funktionen gehören Bewegungsverfolgung, Lichtabschätzung und die Fähigkeit, horizontale und vertikale Ebenen zu erkennen. Google stellt umfangreiche Dokumentationen, Tutorials und Beispielprojekte zur Verfügung, die den Einstieg in die ARCore-Entwicklung erleichtern. Die Integration in Android Studio, die offizielle Entwicklungsumgebung für Android, ermöglicht eine effiziente Entwicklung und Optimierung von AR-Anwendungen. Die Zukunftssicherheit von ARCore ist durch kontinuierliche Unterstützung und Weiterentwicklung der Plattform von Google gewährleistet. Google veröffentlicht regelmäßig Updates und neue Versionen von ARCore, die zusätzliche Funktionen und verbesserte Leistungsfähigkeit bieten. Die breite Unterstützung durch die Android-Entwickler-Community trägt ebenfalls zur Stabilität und Weiterentwicklung der Plattform bei. Was die Kosten betrifft, so entstehen für die Nutzung von ARCore selbst keine zusätzlichen Lizenzkosten, da es in das Android-Entwicklerprogramm integriert ist. Allerdings sind kompatible Android-Geräte und die Nutzung von Android Studio erforderlich, was möglicherweise höhere Hardware- und Softwarekosten im Vergleich zu plattformübergreifenden Lösungen wie WebXR bedeuten kann.

=== Vuforia
Vuforia ist eine von PTC entwickelte Plattform für Augmented Reality-Anwendungen, welche plattformübergreifend auf einer Vielzahl von Geräten verfügbar ist @vuforia-documentation.

In Bezug auf die Leistungsfähigkeit bietet Vuforia eine hohe Erkennungsgenauigkeit und stabile Tracking-Funktionen. Falls verfügbar nutzt die Platform hierbei Native APIs wie ARCore und ARKit. Falls diese nicht vorhanden sind, wird auf eigene Tracking-Technologien zurückgegriffen. Grundsätzlich werden die selben Funktionen wie bei ARCore und ARKit angeboten. Die Plattform stellt umfangreiche Dokumentationen, Tutorials und Beispielprojekte bereit, die den Einstieg in die Entwicklung erleichtern. Vuforia ist in Unity integriert, was es ermöglicht, die bekannten Tools und Workflows dieser Engine zu nutzen. Die Plattform wird regelmäßig aktualisiert, um neue Funktionen und Verbesserungen zu bieten. Die breite Akzeptanz und Nutzung in verschiedenen Branchen trägt ebenfalls zur Stabilität und Weiterentwicklung der Plattform bei. Vuforia bietet verschiedene Lizenzmodelle an. Es gibt eine kostenlose Version mit grundlegenden Funktionen sowie kostenpflichtige Lizenzen, die erweiterte Funktionen und kommerzielle Nutzung ermöglichen. Die Nutzung von Vuforia in Kombination mit Unity kann zusätzliche Lizenzkosten mit sich bringen, was bei der Planung des Budgets berücksichtigt werden sollte.

=== Vergleich
Nach der Vorstellung der AR-Plattformen werden diese anhand der definierten Kriterien verglichen. Dabei wird auf die Kompatibilität, Leistungsfähigkeit, Benutzerfreundlichkeit, Zukunftssicherheit und Kosten eingegangen.

Im Bezug auf die Kompatibilität lässt sich festhalten, dass WebXR, ARCore und Vuforia plattformübergreifende Entwicklungen ermöglichen. ARKit sticht hierbei heraus, da nur für kompatible iOS-Geräte entwickelt werden kann. Des Weiteren muss hervorgehoben werden, dass WebXR aktuell noch nicht bzw. nur experimentell unter iOS-Geräten unterstützt wird @can-i-use-webxr. Dementsprechend bieten ARCore oder Vuforia die beste Kompatibilität für plattformübergreifende Anwendungen.

Hinsichtlich der Leistungsfähigkeit bieten ARKit und ARCore die beste Render-Qualität und die niedrigsten Latenzzeiten, da sie speziell für die Hardware der Geräte entwickelt wurden. WebXR nutzt, wie zuvor beschrieben, ARCore im Hintergrund und kann somit als externer Layer nicht die gleichen Ergebnisse erzielen. Vuforia nutzt, wie WebXR, native Plattformen, falls vorhanden, ermöglicht aber auch eigene Tracking-Funktionen. Der Fokus der Arbeit liegt in der Implementierung einer Möbelkonstruktionsumgebung für Augmented Reality. Hierbei lässt sich die benötigte Performance als gering einstufen. Dementsprechend kann die Anwendung aus Sicht der Leistungsfähigkeit von allen Plattformen umgesetzt werden.

Die Benutzerfreundlichkeit ist bei ARKit und ARCore aufgrund der Integration in die offiziellen Entwicklungsumgebungen von Apple und Google hoch. WebXR bietet eine gute Integration in bestehende Web-Technologien und -Frameworks, was die Entwicklung erleichtert. Vuforia ist gut in Unity integriert, was den Zugang zu bekannten Tools und Workflows ermöglicht. Hierbei ermöglichen ARKit und ARCore eine tiefere Integration in die jeweiligen Betriebssysteme, was die Entwicklung von AR-Anwendungen erleichtern kann.

Die Zukunftssicherheit ist bei ARKit, ARCore und Vuforia durch die kontinuierliche Unterstützung und Weiterentwicklung der Plattformen gewährleistet. WebXR als offener W3C-Standard wird ebenfalls von großen Technologieunternehmen unterstützt und kontinuierlich weiterentwickelt.

Die Kosten für die Nutzung von ARKit und ARCore sind in das jeweilige Entwicklerprogramm integriert und erfordern keine zusätzlichen Lizenzkosten. Vuforia bieten verschiedene Lizenzmodelle an, die von kostenlosen Versionen bis hin zu kostenpflichtigen Lizenzen reichen. Darüber hinaus können weitere Kosten durch die Nutzung von Unity entstehen. WebXR steht als offener Standard kostenlos zur Verfügung und erfordert keine zusätzlichen Lizenzkosten.