Augmented Reality erweitert die Grenzen traditioneller Anwendungen und erstreckt sich zunehmend auf diverse Bereiche. Die spezifischen Anforderungen an AR-Technologien variieren stark je nach Anwendungsbereich. In dieser Arbeit liegt der Fokus auf der Untersuchung relevanter Bereiche für die Arbeit. Hierbei werden sowohl aktuelle Entwicklungen als auch zukünftige Trends beleuchtet werden. Des Weiteren sollen neue WebXR APIs vorgestellt werden.

=== Augmented Reality als Entscheidungshilfe <ar-helper-chapter>
Augmented Reality bietet neue Möglichkeiten der Visualisierung und Interaktion, die in verschiedenen Bereichen eingesetzt werden können. Harish Kumar führte eine systematische Übersichtsarbeit durch, um den Einfluss von Augmented Reality im Online-Einzelhandel zu untersuchen. Die Analyse ergab, dass Augmented Reality signifikante Vorteile für den Online-Einzelhandel bietet. Die Untersuchung identifizierte mehrere Schlüsselmerkmale von AR, die die Kundenerfahrung verbessern, darunter Interaktivität, Lebendigkeit und Augmentation. Diese Merkmale tragen maßgeblich dazu bei, den Entscheidungskomfort zu erhöhen und die Kaufabsicht sowie das Engagement der Kunden zu fördern @ar-online-review.

Darüber hinaus stellte Kumar fest, dass AR nicht nur die Entscheidungsfindung erleichtert, sondern auch die Zufriedenheit der Kunden steigert, indem es ein immersives und interaktives Einkaufserlebnis schafft. AR ermöglicht es den Kunden, Produkte virtuell auszuprobieren und eine realistische Vorstellung davon zu bekommen, wie diese in ihrem Alltag funktionieren könnten. Dies reduziert Unsicherheiten und das wahrgenommene Risiko, was letztendlich zu einer höheren Kaufbereitschaft führt @ar-online-review. Die systematische Literaturübersicht zeigt jedoch auch, dass AR-Technologien im Online-Einzelhandel weiterhin Herausforderungen begegnen, insbesondere in Bezug auf Datenschutzbedenken und die wahrgenommene Eindringlichkeit @ar-online-review.

Eine weitere Studie von Aemmer, D. et al. untersucht den Einfluss von Augmented Reality auf den Kaufentscheidungsprozess von Möbeln. Hierbei wurde die Anwendung FURNIT-AR als Beispiel für eine AR-App zur Visualisierung von Möbeln in der eigenen Umgebung verwendet. Diese Anwendung ermöglicht das Platzieren von virtuellen Möbelstücken in der realen Umgebung @ar-helper. 

Die Studie zeigt, dass AR-Anwendungen wie FURNIT-AR die Konversionsrate positiv beeinflussen können, indem sie als nützliches Hilfsmittel zur Bewertung von Alternativen wahrgenommen werden. Insbesondere in Verbindung mit Onlineshops und dem stationären Handel kann AR dazu beitragen, fundierte Bewertungen vorzunehmen und Dritte in den Entscheidungsprozess einzubeziehen, was die Sicherheit beim Möbelkauf erhöht. Es gibt jedoch kritische Stimmen zur aktuellen Qualität der App. Die grafische Darstellung der Möbelstücke ist oft unzureichend, was den Mehrwert der App mindert. Zudem wird die App bisher nur als unterstützendes Hilfsmittel und nicht als transformative Lösung gesehen @ar-helper.

Insgesamt kommen beide Studien zum Ergebnis, dass sich Augmented Reality einen positiven Einfluss auf den Entscheidungsprozess besitzt, jedoch die technische Umsetzung und Qualität sowie Sicherheit der Anwendung eine entscheidende Rolle spielen @ar-helper @ar-online-review.

=== User Experience in Augmented Reality
Augmented Reality stellt neue Herausforderungen für die User Experience dar. Konventionelle Methoden und Techniken der Interaktion oder Informationsdarstellung lassen sich nur begrenzt oder gar nicht auf AR übertragen.

Admir Dirin und Teemu H. Laine haben die Herausforderungen und Chancen von Augmented Reality für die User Experience von mobilen AR-Anwendungen untersucht. Diese umfassen technische, konzeptionelle sowie physische und mentale Aspekte. Die Nutzung von AR-Technologien erfordert häufig eine höhere körperliche und geistige Anstrengung im Vergleich zu herkömmlichen Anwendungen. Körperlich wird dies durch die Notwendigkeit von Bewegungen und Interaktionen mit dem Raum bedingt, um beispielsweise virtuelle Objekte zu platzieren. Geistige Anstrengung entsteht durch die Neuartigkeit und Unvertrautheit mit der Technologie @ar-ux-mobile. 

Auch auf technischer Seite gibt es Herausforderungen. Obwohl die Tracking-Technologien mit der steigenden Leistungsfähigkeit der Geräte immer besser werden, sind sie nach wie vor anfällig für Fehler. In Kombination mit einer möglichen Unvertrautheit mit dieser Technologie kann dies zu Frustrationen führen @ar-ux-mobile.

Die Studie von Jacky Cao et al. untersucht den Vergleich verschiedener AR-Frameworks mit besonderem Fokus auf mobile Augmented Reality. Dabei wird die Fragmentierung der AR-Technologie hervorgehoben. Es existiert eine Vielzahl an AR-Frameworks, die sich in Funktionalität und Kompatibilität unterscheiden. Technische Aspekte, wie beispielsweise Lichtschätzung und die Anpassung von Registrierungsfehlern, werden als vorteilhaft und entscheidend für die User Experience betrachtet @ar-ui-frameworks. Diese Ergebnisse korrelieren mit den Erkenntnissen der Studie von Dirin und Laine, die ebenfalls die technische Umsetzung als kritischen Faktor für die User Experience hervorheben. Die Darstellung detaillierter und realistischer Objekte kann die Immersion und Interaktivität steigern, was wiederum die Benutzerzufriedenheit erhöht. Die Toleranz gegenüber Fehlern, wie beispielsweise Registrierungsfehlern, wird ebenfalls als wichtiger Faktor genannt @ar-ux-mobile, @ar-ui-frameworks.

Zusammenfassend lässt sich feststellen, dass AR-Anwendungen eine hohe Immersion und Interaktivität bieten können, die das Engagement und die Zufriedenheit der Benutzer steigern. Durch die Integration von AR in mobile Anwendungen können neue Formen der Interaktion und Informationsdarstellung geschaffen werden, die die Benutzererfahrung verbessern. Dies reflektiert die im AR Helper Chapter beschriebenen Vorteile von AR im Entscheidungsprozess.